[versions]
agp = "8.9.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
gson = "2.10.1"
hbb20 = "2.7.3"
googleAuth = "21.3.0"
fbSdk = "18.0.2"
safetynet = "18.1.0"
glide = "4.16.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
hbb20 = { group = "com.hbb20", name = "ccp", version.ref = "hbb20" }
googleAuth = { group = "com.google.android.gms", name = "play-services-auth", version.ref ="googleAuth" }
fbSdk = { group = "com.facebook.android", name = "facebook-android-sdk", version.ref = "fbSdk" }
safetynet = { group = "com.google.android.gms", name = "play-services-safetynet", version.ref = "safetynet" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

